# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      # language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          # integrations/tasks.py false positives
          "--generated-members=client.tasks,client.projects",
          "--disable=logging-fstring-interpolation,import-error",
        ]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
