<script type="ts">
	import { Row, Col, Card, Button, Spinner } from '@sveltestrap/sveltestrap';
  export let on_submit;
  export let checking;
</script>

<Card>
	<h2 class="my-4 text-center">RELEASE OF LIABILITY AND ASSUMPTION OF RISK
    FOR PARTICIPATION IN SHOP ACTIVITIES</h2>
  <Row class="justify-content-center text-center">
    <em>Published 2024-03-14</em>
  </Row>
	<Card class="m4 p4" style="overflow-y:scroll; max-height: 400px">
    <p>The individual named below (referred to as “I” or “me”) desires to work in and with the facilities, tools and equipment provided by Protohaven (the “Activity”). In consideration of engaging in the Activity, I, on behalf of myself, as well as any minor children identified below, agree to all the terms and conditions set forth in this agreement (this “Release”).</p>
    <p>1. I have been informed and understand the various aspects of this Activity. I am aware and understand that despite careful planning and supervision, the Activity is a potentially dangerous activity and involves the risk of personal injury, pain, suffering, temporary or permanent disability, death, property damage, and/or financial loss. I am aware that the Activity generally involves complicating circumstances that may present the risk of hazards, including but not limited to reliance on equipment, reliance on third parties, as well as other risks not known or foreseeable at this time and that the Activity. I am also aware of the highly contagious nature of COVID-19 (the “Disease”) and the risk that I may be exposed to or contract the Disease by engaging in the Activity, which may result in illness, personal or psychological injury, pain, suffering, temporary or permanent disability, death, property damage, and/or financial loss. I understand that while Protohaven has implemented and maintains measures to reduce the risk of injury or harm from the Activity and the spread of the Disease, Protohaven cannot guarantee that I will not be injured or become infected with the Disease or other infectious diseases during my participation in the Activity and that engaging in the Activity may increase my risk of contracting the Disease. NOTWITHSTANDING THESE RISKS, I ACKNOWLEDGE THAT I AM VOLUNTARILY PARTICIPATING IN THE ACTIVITY WITH KNOWLEDGE OF THE DANGERS INVOLVED. I HEREBY AGREE TO ACCEPT AND ASSUME ALL RISKS OF ILLNESS, PERSONAL OR PSYCHOLOGICAL INJURY, PAIN, SUFFERING, TEMPORARY OR PERMANENT DISABILITY, DEATH, PROPERTY DAMAGE, AND/OR FINANCIAL LOSS ARISING THEREFROM, WHETHER CAUSED BY THE NEGLIGENCE OF PROTOHAVEN OR OTHERWISE.</p>
<p>2. RELEASE OF LIABILITY/WAIVER OF RIGHTS: I hereby expressly waive and release any and all claims, now known or hereafter known, for myself, my heirs, family, estate, or other assigns, against Protohaven and its officers, directors, manager(s), employees, agents, affiliates, shareholders/members, successors, and assigns, together with all third-party entities with whom Protohaven contracts to deliver the Activity (collectively, “Releasees”) on account of personal or psychological injury, illness, pain, suffering, temporary or permanent disability, death, property damage, or financial loss arising out of or attributable to my enrolling and participating in the Activity, whether arising out of the negligence of Protohaven or any Releasees or otherwise. I covenant not to make or bring any such claim against Protohaven or any other Releasee, and forever release and discharge Protohaven and all other Releasees from liability under such claims. This waiver and release does not extend to any liabilities that Pennsylvania law does not permit to be released by agreement.</p>
<p>3. Medical; Status. I confirm that I am: (a) in good health and proper physical condition and do not have any medical or other conditions that would impair my ability to participate in the Activity; and (b) I will not participate in the Activity if (i) I am experiencing symptoms of the Disease (such as cough, shortness of breath, sore throat, congestion, headache, muscle or body aches, chills, or fever), (ii) I have a confirmed or suspected case of the Disease at the time the Activity starts, or (iii) I have come in contact with a person who has been confirmed to have or suspected of having the Disease within 14 days of the start of the Activity. I will comply with all federal, state, and local laws, orders, directives, and guidelines related to the Activity and the Disease while participating in the Activity, including, without limitation, requirements related to hand sanitation, social distancing, and use of face coverings and safety equipment. I will also follow all of Protohaven’s instructions, recommendations, and cautions at all times. If at any time I believe conditions to be unsafe, that I am no longer in proper physical condition to participate in the Activity, or I begin experiencing symptoms of the Disease, I will immediately discontinue further participation in the Activity. I acknowledge that Protohaven is relying on these statements to allow me to participate in the Activity.</p>
<p>4. Medical Insurance and Consent. I hereby consent to receive medical treatment deemed necessary if I am injured or require medical attention during my participation in the Activity. I understand and agree that I am solely responsible for all costs related to such medical treatment and any related medical transportation and/or evacuation. I hereby release, forever discharge, and hold harmless Protohaven from any claim based on such treatment or other medical services. I hereby confirm and represent that I am covered by medical insurance that will pay for medical services associated with my participation in the Activity.</p>
<p>5. Indemnification. I shall defend, indemnify, and hold harmless Protohaven and all other Releasees against any and all losses, damages, liabilities, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including attorneys’ fees, fees, the costs of enforcing any right to indemnification under this Release, and the cost of pursuing any insurance providers, incurred by Protohaven or any other Releasees, arising out of or resulting from any claim of a third party, including but not limited to any other participant in the Activity or any person who may appear in media generated by me related to my participating in the Activity, including any claim related to my own negligence, my failure to comply with Protohaven’s rules and instructions, the Activity Rules, or Protohaven’s ordinary negligence.</p>
<p>6. Photo &amp; Video Release. By participating in the Activity, I hereby grant Protohaven the irrevocable right and permission to photograph and/or record Me and to use, reuse, publish, republish and copyright any photographs or recordings taken of me during the Activity (“Activity Media”). This right applies to reproductions in any form, used alone, in a composite or with any printed matter or advertising copy, for purposes of trade, advertising, publicity, promotion or education, in perpetuity and throughout the world, and without restrictions or limitations. I release Protohaven and their agents from any liability resulting from the use of Activity Media and any distortion, blurring, alteration, or placement in a composite, intentional or otherwise, which may occur in the taking, processing, reproduction, publication, or distribution of said Activity Media. I waive any right to inspect or approve the Activity Media or its usage and acknowledge that the rights granted by this release are without compensation of any kind.</p>
<p>7. Adherence to Rules and Requirements. I hereby agree to follow all rules and requirements (“Activity Rules”) made a part of the Activity, and to follow the instructions of any Protohaven agent or employee. I acknowledge that my failure to adhere to the Activity Rules may result in termination of my participation in the Activity, at Protohaven’s sole discretion. I further release Protohaven from any liability arising from my failure to adhere to the Activity Rules and any costs or injury which may occur if my participation in the Activity is terminated.</p>
<p>8. This Release constitutes the sole and entire agreement of Protohaven and me (and/or my minor children) with respect to the subject matter contained herein and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, with respect to such subject matter. I understand the terms of this Release extends forever into the future and will have full force and legal effect each and every time I participate in an Activity. If any term or provision of this Release is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of this Release or invalidate or render unenforceable such term or provision in any other jurisdiction. This Release is binding on and shall inure to the benefit of Protohaven and me (and/or my minor children), together with our respective successors and assigns. All matters arising out of or relating to this Release shall be governed by and construed in accordance with the internal laws of the Commonwealth of Pennsylvania without giving effect to any choice or conflict of law provision or rule (whether of the Commonwealth of Pennsylvania or any other jurisdiction). Any claim or cause of action arising under this Release may be brought only in the federal and state courts located in Allegheny County, Pennsylvania, and I hereby consent to the exclusive jurisdiction of such courts.</p>
</Card>

	<Row>
      <strong class="text-center">THIS IS A RELEASE OF LEGAL RIGHTS<br/>READ IT CAREFULLY AND BE CERTAIN YOU UNDERSTAND BEFORE SIGNING</strong>
		<Col class="d-flex justify-content-center py-3">
      <Button sm={{ size: 'auto'}} color='primary' on:click={on_submit} disabled={checking}>
        I have read and understand this agreement and agree to be bound by its requirements.</Button>
      {#if checking}
        <Spinner type="border" color="primary" class="mx-3" />
      {/if}
		</Col>
	</Row>
</Card>
